language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.6
  - 2.7
gemfile:
  - Gemfile
before_install:
  - gem update bundler
  - mysql -e "create database IF NOT EXISTS shinq_test;" -uroot
script: bundle exec rspec
